networks:
  microservices-net:
    driver: bridge

services:
  postgresql:
      image: postgres:15
      container_name: postgresql
      environment:
        POSTGRES_USER: venkat
        POSTGRES_PASSWORD: password
        POSTGRES_DB: runners
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      networks:
        - microservices-net
      restart: unless-stopped